import type { Harvest, Trip, Match, Notification } from "../domain/models";
export const harvests: Harvest[] = [
  {
    id: "H-1042",
    farmerId: "F-1",
    farmerName: "Pak Budi",
    commodity: "Cabai Merah",
    weightKg: 200,
    location: "Batu, Malang",
    readyAt: "2026-08-02T07:00",
    status: "Menunggu",
    pricePerKg: 44500,
    risk: "Tinggi",
  },
  {
    id: "H-1041",
    farmerId: "F-2",
    farmerName: "Ibu Sari",
    commodity: "Bawang Merah",
    weightKg: 450,
    location: "Nganjuk",
    readyAt: "2026-08-02T09:00",
    status: "Cocok",
    pricePerKg: 36200,
    risk: "Sedang",
  },
  {
    id: "H-1038",
    farmerId: "F-3",
    farmerName: "Pak Darto",
    commodity: "Tomat",
    weightKg: 320,
    location: "Pujon, Malang",
    readyAt: "2026-08-01T15:00",
    status: "Dijemput",
    pricePerKg: 12800,
    risk: "Sedang",
  },
];
export const trips: Trip[] = [
  {
    id: "T-208",
    driverId: "D-1",
    driverName: "Andi Pratama",
    vehicle: "Colt Diesel Box",
    plate: "N 8421 UX",
    origin: "Malang",
    destination: "Surabaya",
    capacityKg: 2200,
    availableKg: 1800,
    departureAt: "2026-08-02T08:00",
    maxDetourKm: 25,
    status: "Tersedia",
  },
  {
    id: "T-207",
    driverId: "D-2",
    driverName: "Rudi Hartono",
    vehicle: "Pickup Box",
    plate: "AG 9134 KL",
    origin: "Kediri",
    destination: "Surabaya",
    capacityKg: 1200,
    availableKg: 750,
    departureAt: "2026-08-02T10:00",
    maxDetourKm: 20,
    status: "Ditawarkan",
  },
];
export const matches: Match[] = [
  {
    id: "M-501",
    harvestId: "H-1041",
    tripId: "T-207",
    farmerName: "Ibu Sari",
    driverName: "Rudi Hartono",
    commodity: "Bawang Merah",
    weightKg: 450,
    pickup: "Nganjuk",
    destination: "Pasar Induk Osowilangun",
    detourKm: 14.2,
    eta: "2j 45m",
    farmerCost: 382500,
    baselineCost: 675000,
    driverRevenue: 351900,
    platformFee: 30600,
    status: "Ditawarkan",
  },
];
export const notifications: Notification[] = [
  {
    id: "N1",
    role: "farmer",
    title: "Truk ditemukan",
    message: "Rudi dapat mengangkut Bawang Merah ke Surabaya.",
    time: "5 menit lalu",
    read: false,
  },
  {
    id: "N2",
    role: "driver",
    title: "Muatan baru",
    message: "450 kg Bawang Merah tersedia dengan detour 14,2 km.",
    time: "8 menit lalu",
    read: false,
  },
  {
    id: "N3",
    role: "operator",
    title: "Risiko tinggi",
    message: "Cabai H-1042 perlu dicocokkan sebelum pukul 10.00.",
    time: "12 menit lalu",
    read: false,
  },
];
